name: Pull Request Build

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install
      
      - name: Fetch base branch
        run: git fetch origin main:main
      
      - name: Validate using DangerJS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn danger ci --dangerfile dangerfile.js --base main
          if [ $? -ne 0 ]; then exit $?; fi
        shell: bash

      - name: Run tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint